language: go

jobs:
  include:
    - arch: ppc64le
      go: 1.17.x

install:
  - go mod tidy
  - go mod download

script:
  - go test -v -short ./...

#after_success:
#  - go test -v -short -bench . -run=^$ ./...
